### ISSUE TITLE
Проект "Классификатор текстовых шрифтов"

### ISSUE THREAD

**Issue by SaviDan245** [SaviDan245/ml-lessons#10]
Здравствуйте, Григорий!

В школе нам часто задают делать презентации (мини-проекты), особенно по гуманитарным предметам. В презентациях зачастую присутствует текст, и, по словам моего друга, у меня нет вкуса, и, вообще, редко когда получается выбрать подходящий, органичный и попросту красивый шрифт для текста. Однако у меня было представление, какого рода шрифты по его мнению "хорошие", но какие именно -- нет.

Поэтому у меня родилась идея, с помощью средств машинного обучения и компьютерного зрения (OpenCV и свёрточных нейроных сетей) создать модель, способную классифицировать текстовые шрифты, используя, к примеру, базу данных [Google Fonts](https://fonts.google.com).

В начале этот проект носил бы больше исследовательский характер и имел бы, например, название "Исследование корреляции архитектуры и гиперпараметров глубокой сверточной нейронной сети с эффективностью классификации текстовых шрифтов". Впоследствии этот проект можно было бы развить до коммерческого: мобильное приложение, использующее основную (заднюю) камеру смартфона для детекции и классификации текстовых шрифтов. Потом можно вообще из этого приложения сделать некое подобие социальной сети для общения, создания и обмена текстовыми шрифтами между дизайнерами. Тем более, насколько мне известно, подобных проектов на рынке ещё не создавалось.

По Вашему мнению, вообще возможно ли решение этой задачи и что Вы думаете о вышеизложенном.

Заранее спасибо!

**Comment by gf0507033** [comment]
Задача классификатора шрифтов очень хорошая и вполне прикладная. Подобные проекты есть (например, [вот](https://www.myfonts.com/WhatTheFont/), и я когда-то занимался чем-то подобным :) ). Сделать рекоммендер, который по нескольким красивым для вас шрифтам подбирает тоже красивые, тоже очень интересно. Подводных камней много, но тем лучше. Простую версию можно сделать за весьма ограниченные сроки.
