### ISSUE TITLE
Интернат при СУНЦ МГУ

### ISSUE THREAD

**Issue by SaviDan245** [SaviDan245/ml-lessons#8]
Здравствуйте, Григорий!

Во время нашего последнего занятия я забыл задать Вам вопрос, связанный с проживанием в интернате при СУНЦ МГУ, а в частности -- с условиями, качеством проживания и т.п. Мне хотелось бы поподробнее узнать об этом.

Заранее спасибо!

**Comment by gf0507033** [comment]
Если коротко, там не хоромы, но для человека без запросов вполне ок, на уровне общежитий МГУ и МФТИ. Комнаты по 5-6 человек, достаточно просторные. Место, где посидеть и поработать, всегда есть, кормят неплохо. Есть свои причуды типа воспитателей, проверяющих комнаты, но это мелочи.
