### ISSUE TITLE
Кружок по программированию и репетиторская деятельность

### ISSUE THREAD

**Issue by SaviDan245** [SaviDan245/ml-lessons#9]
Здравствуйте, Григорий!

Несколько недель назад у моего школьного учителя по математике, ввиду возросшего интереса среди школьников 7-9 классов к алгоритмическому программированию, возникла идея, создать в школе кружок по программированию, ведущим которого стал бы я.

В силу моей абсолютной некомпетентности в вопросе преподавания (вообще; не только программирования), я обратился к Петру Калинину, задав ему несколько интересующих меня вопросов, связанных с данной темой. Он с удовольствием ответил на все поставленные мною вопросы, и, более того, предложил использовать [algoprog.ru](https://algoprog.ru) в качестве образовательной платформы. Он сделает отдельные сводные таблицы по моим ученикам, а я в свою очередь получу права админа и смогу наряду с ним проверять и комментировать решения моих учеников.

Реализацию этой задумки, к сожалению, пришлось ненадолго отложить, а именно -- на две, включая эту, недели, так как у меня начались экзамены, которые завершаться до конца февраля.

Григорий, по Вашему мнению, учитывая мои цели и желания, стоит ли создавать кружок по программированию (или даже начать заниматься репетиторством), или всё же лучше, не распыляясь, заниматься собою и продолжать регулярно и интенсивно учиться?

Заранее спасибо!

**Comment by gf0507033** [comment]
Это может быть хорошей идеей. Какие есть неочевидные сложности:
- вести кружок для большого числа ребят -- не очень продуктивно и очень тяжело. Оптимально -- 3-6 человек.
- потраченное время можно оценить так: на подготовку хорошего занятия тратится приблизительно столько времени, сколько оно длится. Прибавьте время на решение оргвопросов --- и вот затраты.
- завалы с экзаменами или другими делами у вас будут относительно регулярно. Соответственно, и кружок будет прерываться.

Плюсы очевидны: объясняя что-то, понимаешь это лучше. Ну и дело вполне полезное.

Минусы тоже очевидны: время, силы, низкая отдача. Ну и с полным списком активностей (алгопрог, мл, проект с дорожными знаками, немецкий, школьные дела, еще что-то) уже придется составить расписание и очень жестко следовать ему.

Я бы начал проводить кружок тогда, когда почувствовал, что на это **точно** хватит времени.
